export default function ReportFooter() {
  return (
    <div className="mt-8 pt-4 border-t border-gray-300 print:mt-4 print:pt-2">
      <div className="flex items-center justify-between text-xs text-gray-400">
        <span>Generated by Poultry Farm Manager</span>
        <span>Confidential — For internal use only</span>
      </div>
    </div>
  );
}
